---
openapi: 3.0.3
info:
  title: Material Flow Simulation Result Aspect
  version: v3
servers:
- url: catenax.io/api/v3
  variables:
    api-version:
      default: v3
paths:
  /{tenant-id}/material-flow-simulation-result-aspect:
    get:
      tags:
      - MaterialFlowSimulationResultAspect
      operationId: getMaterialFlowSimulationResultAspect
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: '#/components/responses/MaterialFlowSimulationResultAspect'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text:
      type: string
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnsTrait:
      type: string
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two alphanumeric letters."
      pattern: "^BPNS[a-zA-Z0-9]{12}$"
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_BusinessPartnerSite:
      description: Reference of preceding shipments
      type: object
      properties:
        bpnsProperty:
          description: Property based on BPNS
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnsTrait'
      required:
      - bpnsProperty
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_DataQualityOptions:
      type: number
      minimum: 0
      description: Possible values determining data quality
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text:
      type: string
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean:
      type: boolean
      description: Represents a boolean value (i.e. a "flag").
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_VolumeCharacteristic:
      type: number
      description: Volumetric value determining the volume of the handling unit
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_WeightCharacteristic:
      type: number
      description: Amount of weight of the handling unit
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_AmountCharacteristic:
      type: number
      minimum: 1
      description: Number describing handling units with identical pieces
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_QuantityCharacteristic:
      type: number
      description: Number of materials contained within a handling unit
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_UnitOfMeasurementCharacteristic:
      type: string
      description: Possible options for units of measurement
      enum:
      - KG
      - Liter
      - Piece
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_MaterialBatch:
      description: Material Batches are part of a handling unit
      type: object
      properties:
        batchSerialNumber:
          description: can be used to uniquely identify a singe product part
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text'
        materialNumber:
          description: ID of the material contained in the batch
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text'
        materialName:
          description: Name of the material
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text'
        materialHazardousGoods:
          description: Flags hazardous goods
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean'
        batchExpirationTimestamp:
          description: Expiration date of batch
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        quantity:
          description: Amount of materials
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_QuantityCharacteristic'
        unitOfMeasurement:
          description: Unit used for measuring the quantity
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_UnitOfMeasurementCharacteristic'
        batchNumber:
          description: "Number of the batch, generated by originator (e.g. from ERP\
            \ system, no uuid)"
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text'
        batchOrderId:
          description: Order ID to which the batch belongs
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text'
      required:
      - batchSerialNumber
      - materialNumber
      - materialName
      - materialHazardousGoods
      - batchExpirationTimestamp
      - quantity
      - unitOfMeasurement
      - batchNumber
      - batchOrderId
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_BatchList:
      description: List of material batches
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_MaterialBatch'
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_HandlingUnit:
      description: Handling Unit is the smallest shipment unit and cannot be divided
        into several shipments
      type: object
      properties:
        handlingUnitId:
          description: ID of the handling unit
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text'
        name:
          description: Name of the type of handling unit
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text'
        volume:
          description: Volume of the handling unit
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_VolumeCharacteristic'
        weight:
          description: Weight of the handling unit
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_WeightCharacteristic'
        amount:
          description: Number of handling units with identical content
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_AmountCharacteristic'
        batches:
          description: List of material batches contained within a handling unit
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_BatchList'
      required:
      - handlingUnitId
      - name
      - volume
      - weight
      - amount
      - batches
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_HandlingUnitList:
      description: List of handling units included in the shipment
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_HandlingUnit'
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Shipment:
      description: Delivery item from a sender to a recipient containing goods
      type: object
      properties:
        shipmentId:
          description: ID to identify the shipment
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        destination:
          description: Address where the shipment is immediately delivered to (by
            logistician) or provided for pickup (by producer)
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_BusinessPartnerSite'
        destinationTimestamp:
          description: Time when delivery arrives or is ready at goods issue
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        recipient:
          description: Address of final recipient of shipment
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_BusinessPartnerSite'
        recipientTimestampPlanned:
          description: Planned delivery time
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        splittingAllowed:
          description: Permission to split the shipment into individual deliveries
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean'
        logistics:
          description: Address of logistician executing the shipment
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_BusinessPartnerSite'
        preceding:
          description: Reference ID of a preceding shipment
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_BusinessPartnerSite'
        handlingUnits:
          description: List of Handling Units
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_HandlingUnitList'
      required:
      - shipmentId
      - destination
      - destinationTimestamp
      - recipient
      - recipientTimestampPlanned
      - splittingAllowed
      - logistics
      - preceding
      - handlingUnits
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_ShipmentList:
      description: List of shipments contained in the simulation
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Shipment'
    urn_samm_io.catenax.material_flow_simulation_result_3.0.0_MaterialFlowSimulationResultCharacteristic:
      description: Characteristic describing the aspect material flow simulation result
      type: object
      properties:
        description:
          description: Verbal description
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text'
        runId:
          description: Id of the simulation run
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text'
        comment:
          description: Additional comments
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_Text'
        expirationTimestamp:
          description: Date and time when the simulation is expired
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        owner:
          description: Site identifier of the simulation originator
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_BusinessPartnerSite'
        dataQuality:
          description: Information on quality of simulation results
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_DataQualityOptions'
        shipments:
          description: List of shipments
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_ShipmentList'
        timestamp:
          description: Timestamp of simulation run
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
      required:
      - description
      - runId
      - comment
      - expirationTimestamp
      - owner
      - dataQuality
      - shipments
      - timestamp
    MaterialFlowSimulationResultAspect:
      description: Aspect Model for the result of a Material Flow Simulation
      type: object
      properties:
        materialFlowSimulationResult:
          description: Contains standardized attributes for the result of a material
            flow simulation
          $ref: '#/components/schemas/urn_samm_io.catenax.material_flow_simulation_result_3.0.0_MaterialFlowSimulationResultCharacteristic'
      required:
      - materialFlowSimulationResult
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    MaterialFlowSimulationResultAspect:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MaterialFlowSimulationResultAspect'
      description: The request was successful.
  requestBodies:
    MaterialFlowSimulationResultAspect:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MaterialFlowSimulationResultAspect'
